spring.application.name=Synchro

spring.datasource.url=jdbc:postgresql://localhost:15432/synchro_db
spring.datasource.username=synchro
spring.datasource.password=synchro123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.thymeleaf.cache=false

logging.level.org.springframework.security=DEBUG
logging.level.org.thymeleaf=DEBUG
logging.level.org.thymeleaf.spring5=DEBUG

kinopoisk.api-key=4GQ1PPZ-PS8MHER-HRX6M6F-1PEFKJH

# ????????? ???????? ??????
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis